//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanIVent
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Clienti
    {
        public int ID_Client { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
        public System.DateTime Varsta { get; set; }
        public string Adresa { get; set; }
        public string Telefon { get; set; }
        public Nullable<int> ID_Login { get; set; }
    
        public virtual Login Login { get; set; }
    }
}
