//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanIVent
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Evenimente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Evenimente()
        {
            this.Sarcinis = new ObservableCollection<Sarcini>();
            this.Serviciis = new ObservableCollection<Servicii>();
        }
    
        public int ID_Eveniment { get; set; }
        public string Denumire { get; set; }
        public System.DateTime Data_Start { get; set; }
        public System.DateTime Data_Sfarsit { get; set; }
        public Nullable<int> ID_Categorie { get; set; }
        public Nullable<int> ID_Locatie { get; set; }
        public Nullable<int> NrPersoane { get; set; }
        public Nullable<int> ID_Status { get; set; }
    
        public virtual Categorii Categorii { get; set; }
        public virtual Locatii Locatii { get; set; }
        public virtual Status_Ev Status_Ev { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Sarcini> Sarcinis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Servicii> Serviciis { get; set; }
    }
}
