//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanIVent
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Locatii
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Locatii()
        {
            this.Evenimentes = new ObservableCollection<Evenimente>();
        }
    
        public int ID_Locatie { get; set; }
        public string Denumire { get; set; }
        public decimal Pret { get; set; }
        public string Judet { get; set; }
        public string Adresa { get; set; }
        public string Nume_Proprietar { get; set; }
        public string Telefon_Proprietar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Evenimente> Evenimentes { get; set; }
    }
}
