//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanIVent
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Servicii
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Servicii()
        {
            this.Evenimentes = new ObservableCollection<Evenimente>();
        }
    
        public int ID_serviciu { get; set; }
        public int ID_categorie_Ev { get; set; }
        public string Denumire { get; set; }
        public Nullable<decimal> Pret { get; set; }
    
        public virtual Categorii Categorii { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Evenimente> Evenimentes { get; set; }
    }
}
